### ISSUE TITLE
[Quest/Chaining] Northern Barrens - Horde side - Global report

### ISSUE THREAD

**Issue by Arkanheal** [GuabinaCore/WoWKoi#845]
I thought I'd make a centralized report about all the chaining issues with quests in Northern Barrens.

I'll format the issue this way:

- [Report Title] - Quest ID: [ID with a link to wowhead] - Original report by  [original author] ([Report link])

[**Here**](https://www.wowhead.com/storyline/northern-barrens-509), you'll be able to find the wowhead chaining page for the zone. 

- [ ] [QUEST/Chaining] The Zhevra - Quest ID: [845](https://www.wowhead.com/quest=845/the-zhevra) - Original report by @Maczuga (#777)

- [ ] [QUEST/Chaining] Hunting the Huntress - Quest ID: [903](https://www.wowhead.com/quest=903/hunting-the-huntress) - Original report by @Maczuga (#778)

- [ ]  [QUEST] Fungal Spores chaining issue - Quest ID: [848](https://www.wowhead.com/quest=848/fungal-spores) - Original report by @Maczuga (#780)

**NB**: Please do not close this issue, as I'll add the further problems found if any on Northern Barrens questing chains.

**Comment by Arkanheal** [comment]
*Feedback from devs/admins appreciated (to know if I do the other recurring issues as well)*
